# generated by datamodel-codegen:
#   filename:  ws-messages.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint


class MicSource(StrEnum):
    """
    Which microphone the client is currently capturing from.
    """

    g2_microphone = 'g2-microphone'
    phone_microphone = 'phone-microphone'


class Lang(StrEnum):
    """
    Languages the STT engine may detect/report on captions.
    """

    en = 'en'
    es = 'es'
    fr = 'fr'
    de = 'de'
    pt = 'pt'
    it = 'it'


class Word(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    startMs: conint(ge=0)
    endMs: conint(ge=0)
    confidence: confloat(ge=0.0, le=1.0) | None = None


class SessionStart(BaseModel):
    """
    Client -> server. Opens a live session before any audio frames are sent.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.start']
    sessionId: str | None = Field(
        None,
        description='Optional client-provided id to resume a dropped session; the server echoes the authoritative id in session.ready.',
    )
    micSource: MicSource
    sourceLang: Lang | None = None


class MicSwitch(BaseModel):
    """
    Client -> server. Runtime microphone source change.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['mic.switch']
    micSource: MicSource


class SessionEnd(BaseModel):
    """
    Client -> server. Finalizes the session; the transcript and retained audio are persisted.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.end']


class Ping(BaseModel):
    """
    Client -> server. Liveness probe; server replies with Pong.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ping']
    t: int | None = Field(
        None, description='Client send timestamp (ms epoch), echoed back.'
    )


class ClientMessage(RootModel[SessionStart | MicSwitch | SessionEnd | Ping]):
    root: SessionStart | MicSwitch | SessionEnd | Ping = Field(
        ..., title='ClientMessage'
    )


class SessionReady(BaseModel):
    """
    Server -> client. Session accepted; client may begin streaming audio.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.ready']
    sessionId: str
    resumed: bool | None = False


class CaptionPartial(BaseModel):
    """
    Server -> client. Fast, unstable hypothesis for the live caption band.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['caption.partial']
    text: str
    lang: Lang | None = None


class CaptionFinal(BaseModel):
    """
    Server -> client. Stable finalized segment with timing.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['caption.final']
    segmentId: str
    text: str
    lang: Lang | None = None
    startMs: conint(ge=0)
    endMs: conint(ge=0)
    words: list[Word] | None = None


class Cue(BaseModel):
    """
    Server -> client. A private contextual info card the api derived from the live conversation (e.g. someone asks how far the sun is; the answer appears). Cues are private to the listener, not part of the conversation. Clients show it in a bordered box above the live transcript for ~10s, and persist it inline in the transcript history at atMs.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['cue']
    cueId: str = Field(
        ..., description='Stable id for this cue (dedupe / popup keying).'
    )
    title: str = Field(..., description='1-3 word label for the cue box.')
    body: str = Field(
        ..., description='The contextual detail shown in the box / history popup.'
    )
    atMs: conint(ge=0) = Field(
        ...,
        description='Position on the conversation timeline (ms) the cue relates to, so history can render it inline where it appeared.',
    )
    source: str | None = Field(
        None,
        description='Short label of the live source the cue\'s fact was grounded in (XERK-120), e.g. "BBC News" or "Wikipedia". Absent when the cue rests on the model\'s own knowledge; clients render it as a quiet attribution line under the body.',
    )


class Translation(BaseModel):
    """
    Server -> client. English translation of one finalized non-English turn (XERK-160). Delivered off the caption path once the turn's caption.final is out; clients pair it with that segment by segmentId (web/mobile/phone render it alongside the original turn, the glasses lens shows it in the cue box slot). While a translation run is live the api suppresses cues; the run ends with translation.done.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['translation']
    segmentId: str = Field(
        ..., description='The caption.final segment this translates.'
    )
    text: str = Field(..., description="The English translation of the segment's text.")
    sourceLang: Lang | None = None


class TranslationDone(BaseModel):
    """
    Server -> client. The non-English run is over — the speaker is done being spoken-to in another language (an English turn arrived, or speech went quiet past the hold window). On the glasses this is what starts the translation box's 10s dismiss countdown; cue generation resumes after this.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['translation.done']


class Pong(BaseModel):
    """
    Server -> client. Reply to Ping.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['pong']
    t: int | None = Field(None, description='Echoed client timestamp from Ping.')


class Code(StrEnum):
    bad_request = 'bad_request'
    unauthorized = 'unauthorized'
    session_not_found = 'session_not_found'
    rate_limited = 'rate_limited'
    internal = 'internal'


class ErrorMessage(BaseModel):
    """
    Server -> client. Recoverable or fatal error for the current session.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    code: Code
    message: str
    fatal: bool | None = False


class ServerMessage(
    RootModel[
        SessionReady
        | CaptionPartial
        | CaptionFinal
        | Cue
        | Translation
        | TranslationDone
        | Pong
        | ErrorMessage
    ]
):
    root: (
        SessionReady
        | CaptionPartial
        | CaptionFinal
        | Cue
        | Translation
        | TranslationDone
        | Pong
        | ErrorMessage
    ) = Field(..., title='ServerMessage')


class TenirWsMessages(RootModel[ClientMessage | ServerMessage]):
    root: ClientMessage | ServerMessage = Field(
        ...,
        description='Single source of truth for the tenir WebSocket message contract between the clients (TS) and the FastAPI api (Python). TS types and Pydantic models are generated from this file; do not hand-edit the generated outputs. Audio is sent as raw BINARY WebSocket frames (16kHz, signed 16-bit little-endian, mono PCM); every JSON frame below is a control or result message.',
        title='TenirWsMessages',
    )
