# generated by datamodel-codegen:
#   filename:  ws-messages.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint


class MicSource(StrEnum):
    """
    Which microphone the client is currently capturing from.
    """

    g2_microphone = 'g2-microphone'
    phone_microphone = 'phone-microphone'


class Lang(StrEnum):
    """
    Languages the STT engine may detect/report on captions.
    """

    en = 'en'
    es = 'es'
    fr = 'fr'
    de = 'de'
    pt = 'pt'
    it = 'it'


class Word(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    startMs: conint(ge=0)
    endMs: conint(ge=0)
    confidence: confloat(ge=0.0, le=1.0) | None = None


class SessionStart(BaseModel):
    """
    Client -> server. Opens a live session before any audio frames are sent.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.start']
    sessionId: str | None = Field(
        None,
        description='Optional client-provided id to resume a dropped session; the server echoes the authoritative id in session.ready.',
    )
    micSource: MicSource
    sourceLang: Lang | None = None


class MicSwitch(BaseModel):
    """
    Client -> server. Runtime microphone source change.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['mic.switch']
    micSource: MicSource


class SessionEnd(BaseModel):
    """
    Client -> server. Finalizes the session; the transcript and retained audio are persisted.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.end']


class Ping(BaseModel):
    """
    Client -> server. Liveness probe; server replies with Pong.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ping']
    t: int | None = Field(
        None, description='Client send timestamp (ms epoch), echoed back.'
    )


class ClientMessage(RootModel[SessionStart | MicSwitch | SessionEnd | Ping]):
    root: SessionStart | MicSwitch | SessionEnd | Ping = Field(
        ..., title='ClientMessage'
    )


class SessionReady(BaseModel):
    """
    Server -> client. Session accepted; client may begin streaming audio.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.ready']
    sessionId: str
    resumed: bool | None = False


class CaptionPartial(BaseModel):
    """
    Server -> client. Fast, unstable hypothesis for the live caption band.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['caption.partial']
    text: str
    lang: Lang | None = None


class CaptionFinal(BaseModel):
    """
    Server -> client. Stable finalized segment with timing.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['caption.final']
    segmentId: str
    text: str
    lang: Lang | None = None
    startMs: conint(ge=0)
    endMs: conint(ge=0)
    words: list[Word] | None = None


class Pong(BaseModel):
    """
    Server -> client. Reply to Ping.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['pong']
    t: int | None = Field(None, description='Echoed client timestamp from Ping.')


class Code(StrEnum):
    bad_request = 'bad_request'
    unauthorized = 'unauthorized'
    session_not_found = 'session_not_found'
    rate_limited = 'rate_limited'
    internal = 'internal'


class ErrorMessage(BaseModel):
    """
    Server -> client. Recoverable or fatal error for the current session.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    code: Code
    message: str
    fatal: bool | None = False


class ServerMessage(
    RootModel[SessionReady | CaptionPartial | CaptionFinal | Pong | ErrorMessage]
):
    root: SessionReady | CaptionPartial | CaptionFinal | Pong | ErrorMessage = Field(
        ..., title='ServerMessage'
    )


class TenirWsMessages(RootModel[ClientMessage | ServerMessage]):
    root: ClientMessage | ServerMessage = Field(
        ...,
        description='Single source of truth for the tenir WebSocket message contract between the clients (TS) and the FastAPI api (Python). TS types and Pydantic models are generated from this file; do not hand-edit the generated outputs. Audio is sent as raw BINARY WebSocket frames (16kHz, signed 16-bit little-endian, mono PCM); every JSON frame below is a control or result message.',
        title='TenirWsMessages',
    )
