/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single source of truth for the tenir WebSocket message contract between the clients (TS) and the FastAPI api (Python). TS types and Pydantic models are generated from this file; do not hand-edit the generated outputs. Audio is sent as raw BINARY WebSocket frames (16kHz, signed 16-bit little-endian, mono PCM); every JSON frame below is a control or result message.
 */
export type TenirWsMessages = ClientMessage | ServerMessage;
export type ClientMessage = SessionStart | MicSwitch | SessionEnd | Ping;
/**
 * Which microphone the client is currently capturing from.
 */
export type MicSource = "g2-microphone" | "phone-microphone";
/**
 * Languages the STT engine may detect/report on captions.
 */
export type Lang = "en" | "es" | "fr" | "de" | "pt" | "it";
export type ServerMessage = SessionReady | CaptionPartial | CaptionFinal | Pong | ErrorMessage;

/**
 * Client -> server. Opens a live session before any audio frames are sent.
 */
export interface SessionStart {
  type: "session.start";
  /**
   * Optional client-provided id to resume a dropped session; the server echoes the authoritative id in session.ready.
   */
  sessionId?: string;
  micSource: MicSource;
  sourceLang?: Lang;
}
/**
 * Client -> server. Runtime microphone source change.
 */
export interface MicSwitch {
  type: "mic.switch";
  micSource: MicSource;
}
/**
 * Client -> server. Finalizes the session; the transcript and retained audio are persisted.
 */
export interface SessionEnd {
  type: "session.end";
}
/**
 * Client -> server. Liveness probe; server replies with Pong.
 */
export interface Ping {
  type: "ping";
  /**
   * Client send timestamp (ms epoch), echoed back.
   */
  t?: number;
}
/**
 * Server -> client. Session accepted; client may begin streaming audio.
 */
export interface SessionReady {
  type: "session.ready";
  sessionId: string;
  resumed?: boolean;
}
/**
 * Server -> client. Fast, unstable hypothesis for the live caption band.
 */
export interface CaptionPartial {
  type: "caption.partial";
  text: string;
  lang?: Lang;
}
/**
 * Server -> client. Stable finalized segment with timing.
 */
export interface CaptionFinal {
  type: "caption.final";
  segmentId: string;
  text: string;
  lang?: Lang;
  startMs: number;
  endMs: number;
  words?: Word[];
}
export interface Word {
  text: string;
  startMs: number;
  endMs: number;
  confidence?: number;
}
/**
 * Server -> client. Reply to Ping.
 */
export interface Pong {
  type: "pong";
  /**
   * Echoed client timestamp from Ping.
   */
  t?: number;
}
/**
 * Server -> client. Recoverable or fatal error for the current session.
 */
export interface ErrorMessage {
  type: "error";
  code: "bad_request" | "unauthorized" | "session_not_found" | "rate_limited" | "internal";
  message: string;
  fatal?: boolean;
}
